/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.examples

// Rules for ReteooLayoutFactoryTest

import org.drools.eclipse.editors.rete.ReteooLayoutFactoryTest.Message;

rule "Hello World"
        when
                m : Message( status == Message.HELLO, message : message )
        then
                System.out.println( message );
                m.setMessage( "Goodbye cruel world" );
                m.setStatus( Message.GOODBYE );
                update( m );
end

rule "GoodBye"
        no-loop true
        when
                m : Message( status == Message.GOODBYE, message : message )
        then
                System.out.println( message );
                m.setMessage( message );
end
