package org.drools.examples

// Rules for ReteooLayoutFactoryTest

import org.drools.eclipse.editors.rete.ReteooLayoutFactoryTest.Message;

rule "Hello World"
        when
                m : Message( status == Message.HELLO, message : message )
        then
                System.out.println( message );
                m.setMessage( "Goodbye cruel world" );
                m.setStatus( Message.GOODBYE );
                update( m );
end

rule "GoodBye"
        no-loop true
        when
                m : Message( status == Message.GOODBYE, message : message )
        then
                System.out.println( message );
                m.setMessage( message );
end
